/// Flutter icons Dominoes
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dominoes
///      fonts:
///       - asset: fonts/Dominoes.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Dominoes {
  Dominoes._();

  static const _kFontFam = 'Dominoes';
  static const _kFontPkg = null;

  static const IconData dominoes =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
